### ISSUE TITLE
JWST notebook photoutils.patch error

### ISSUE THREAD

**Issue by SebastianPrehn** [ucphhpc/nbi-jupyter-docker-stacks#66]
# photoutils.patch error

When building the dev build of the jwst-notebook, the build fails with the following relevant error code:
``` > [25/34] RUN mamba run -n python3 python /tmp/photutils.patch     && mamba clean --all -f -y     && fix-permissions /opt/conda     && fix-permissions /home/jovyan:
7.642     from .base import BaseDifferential, BaseRepresentation, BaseRepresentationOrDifferential
7.642   File "/opt/conda/envs/python3/lib/python3.10/site-packages/astropy/coordinates/representation/base.py", line 12, in <module>
7.642     from astropy.coordinates.angles import Angle
7.642   File "/opt/conda/envs/python3/lib/python3.10/site-packages/astropy/coordinates/angles/__init__.py", line 11, in <module>
7.642     from .utils import *
7.642   File "/opt/conda/envs/python3/lib/python3.10/site-packages/astropy/coordinates/angles/utils.py", line 21, in <module>
7.642     from astropy.coordinates.representation import (
7.642 ImportError: cannot import name 'SphericalRepresentation' from partially initialized module 'astropy.coordinates.representation' (most likely due to a circular import) (/opt/conda/envs/python3/lib/python3.10/site-packages/astropy/coordinates/representation/__init__.py)
```
starting on this line in the code
https://github.com/ucphhpc/nbi-jupyter-docker-stacks/blob/eac4bce8d4018df91df885fe64080d6753ecebb2/jwst-notebook/Dockerfile.j2#L95

@gbrammer You initially created this Notebook with the file photoutils.patch and I wanted to ask if you had any idea for a fix to this, as we would like to be able to use the new JupyterLab 4.0.11 introduced in eac4bce for its security fixes.

## Possible solutions

When looking at [photoutils install](https://photutils.readthedocs.io/en/stable/install.html), it recommends `conda install -c conda-forge photutils` which could be a potential solution, unless the patch does something specific and is not just legacy at this point?

**Comment by rasmunk** [comment]
Given no response to potentially adjusting the photoutils install, we have moved to using the official installation guide https://photutils.readthedocs.io/en/stable/getting_started/install.html to installing the photoutils package which fixed the posted build issue via:

https://github.com/ucphhpc/nbi-jupyter-docker-stacks/blob/deba3a0e4e1a53bd756bb2f0bbbaa56545a14183/jwst-notebook/Dockerfile.j2#L88.

If further issues arise from this during runtime please create a separate issue.
